<!-- Page Sidebar -->
<div class="page-sidebar">

    <!-- Site header  -->
    <header class="site-header">
        <div class="site-logo">
            <a href="/<?php echo e(explode('/',request()->route()->uri())[0]); ?>">
                <img src="<?php echo e(asset('assets/images/logo.png')); ?>" width="320">
            </a>
        </div>
    </header>
    <!-- /site header -->

    <!-- Main navigation -->
    

        
            
                
            
        
        
            
            
                
                

                    
                
            
            
                
                
                    
                    
                
            
            
                
                
                    
                    
                
            
            
                
                
                    
                    
                
            
            
                
                    
                
            
            
                
                    
                        
                    
                
            
                
                    
                        
                    
                
                
                    
                        
                    
                
            
        
        
            
                
                
                    
                    
                
            
            
                
                
                    
                    
                
            
            
            
                
                
                    
                    
                
            
            
            
            
                
                
                    
                    
                
            
            
            
            
                
                
                    
                    
                
            
            
            
            
                
                
                    
                    
                
            
            
            
                
                
                    
                    
                
            
        

        

            
            
                
                
                    
                    
                    
                
            
            
            
                
                    
                    
                        
                    
                
            
            
                
                    
                    
                        
                    
                
            
            
                
                    
                    
                        
                    
                
            
            
                
                    
                    
                        
                    
                
            

        

        
        
            
        
            
        
            
        
        
    
    <!-- /main navigation -->
</div>
<!-- /page sidebar -->
<?php /**PATH C:\Users\Mahmoud\Desktop\pspsystem\resources\views/layouts/sidebar.blade.php ENDPATH**/ ?>